namespace Firmness.Application.Mappings;

using AutoMapper;
using Firmness.Application.DTOs.Products;
using Firmness.Application.DTOs.Categories;
using Firmness.Application.DTOs.Customers;
using Firmness.Domain.Entities;

/// <summary>
/// Configuration of mappings between domain entities and DTOs.
/// AutoMapper uses this class to learn how to convert objects.
/// </summary>
public class MappingProfile : Profile
{
    public MappingProfile()
    {
        // Product → ProductDto (to show)
        CreateMap<Product, ProductDto>()
            .ForMember(dest => dest.CategoryId, opt => opt.MapFrom(src => src.CategoryId))
            .ForMember(dest => dest.Category, opt => opt.MapFrom(src => 
                src.Category != null ? src.Category.Name : string.Empty));
        
        // Category → CategoryDto (to show)
        CreateMap<Category, CategoryDto>();
        
        // Customer → CustomerDto (to show)
        CreateMap<ApplicationUser, CustomerDto>();
        
        // CreateProductDto → Product (to create)
        CreateMap<CreateProductDto, Product>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // The ID is generated by the database
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
            .ForMember(dest => dest.IsActive, opt => opt.Ignore())
            .ForMember(dest => dest.Category, opt => opt.Ignore());
        
        // CreateCategoryDto → Category (to create)
        CreateMap<CreateCategoryDto, Category>();
        
        // CreateCustomerDto → Customer (to create)
        CreateMap<CreateCustomerDto, ApplicationUser>();
        
        // UpdateProductDto → Product (to update)
        CreateMap<UpdateProductDto, Product>()
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
            .ForMember(dest => dest.Category, opt => opt.Ignore());
        CreateMap<ProductDto, UpdateProductDto>();
        
        // UpdateCategoryDto → Category (to update)
        CreateMap<UpdateCategoryDto, Category>();
        CreateMap<CategoryDto, UpdateCategoryDto>();
        
        // UpdateCustomerDto → Category (to update)
        CreateMap<UpdateCustomerDto, ApplicationUser>();
        CreateMap<ApplicationUser, UpdateCustomerDto>();
    }
}